# GitHub Sponsors funding file
# 赞助配置（可选）

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-opencollective-name
# ko_fi: your-kofi-name
# custom: ["https://your-donate-link.com"]

