version: '3.8'

services:
  awbackup:
    image: awdress/awbackup:latest
    container_name: AWBackup
    build:
      context: .
      dockerfile: Dockerfile
    
    # 环境变量
    environment:
      # 定时任务 Cron 表达式（默认每天凌晨2点）
      - CRON_SCHEDULE=0 2 * * *
      
      # 时区设置
      - TZ=Asia/Shanghai
    
    # 卷挂载
    volumes:
      # 配置文件（建议先复制 config.conf 到宿主机编辑）
      - ./config.conf:/app/config.conf:ro
      
      # 日志目录
      - ./logs:/app/logs
      
      # 备份目标目录
      - /mnt/user/backups:/backups
      
      # 源数据目录（根据需要挂载多个）
      - /mnt/user/documents:/data/documents:ro
      - /mnt/user/photos:/data/photos:ro
      - /mnt/user/appdata:/data/appdata:ro
    
    # 重启策略
    restart: unless-stopped
    
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # 网络模式（如需 Telegram 通知）
    network_mode: bridge
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ============================================
# 使用示例
# ============================================
# 
# 1. 构建镜像:
#    docker-compose build
# 
# 2. 启动容器:
#    docker-compose up -d
# 
# 3. 查看日志:
#    docker-compose logs -f
# 
# 4. 手动执行备份:
#    docker-compose exec awbackup /app/backup.sh
# 
# 5. 停止容器:
#    docker-compose down
# 
# ============================================

