# AWBackup Docker Compose 配置示例
# 复制此文件为 docker-compose.yml 并根据需要修改

version: '3.8'

services:
  # ========================================
  # 基础配置示例
  # ========================================
  awbackup:
    image: awdress/awbackup:latest
    container_name: awbackup
    build:
      context: .
      dockerfile: Dockerfile
    
    # 环境变量配置
    environment:
      # 定时任务 Cron 表达式
      # 格式: 分 时 日 月 周
      # 示例: 0 2 * * * (每天凌晨2点)
      - CRON_SCHEDULE=0 2 * * *
      
      # 时区设置
      - TZ=Asia/Shanghai
    
    # 卷挂载
    volumes:
      # 配置文件（必需，只读）
      - ./config.conf:/app/config.conf:ro
      
      # 日志目录（推荐）
      - ./logs:/app/logs
      
      # 备份目标目录（必需）
      - /mnt/user/backups:/backups
      
      # 源数据目录（必需，只读）
      # 根据实际情况添加多个
      - /mnt/user/documents:/data/documents:ro
      - /mnt/user/photos:/data/photos:ro
    
    # 重启策略
    restart: unless-stopped
    
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # 网络模式
    network_mode: bridge
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ========================================
# 其他配置示例
# ========================================

# 示例：多实例部署
# 取消注释下面的配置以启用
#
#  awbackup-daily:
#    image: awdress/awbackup:latest
#    container_name: awbackup-daily
#    environment:
#      - CRON_SCHEDULE=0 2 * * *
#      - TZ=Asia/Shanghai
#    volumes:
#      - ./config-daily.conf:/app/config.conf:ro
#      - ./logs/daily:/app/logs
#      - /mnt/user/backups/daily:/backups
#      - /mnt/user/documents:/data/documents:ro
#    restart: unless-stopped
#
#  awbackup-weekly:
#    image: awdress/awbackup:latest
#    container_name: awbackup-weekly
#    environment:
#      - CRON_SCHEDULE=0 3 * * 0
#      - TZ=Asia/Shanghai
#    volumes:
#      - ./config-weekly.conf:/app/config.conf:ro
#      - ./logs/weekly:/app/logs
#      - /mnt/user/backups/weekly:/backups
#      - /mnt/user/documents:/data/documents:ro
#    restart: unless-stopped

