version: '3.8'

services:
  awbackup:
    image: awdress/awbackup:latest
    container_name: AWBackup
    
    environment:
      # 定时任务 (Cron 表达式)
      - CRON_SCHEDULE=0 2 * * *
      
      # 时区
      - TZ=Asia/Shanghai
    
    volumes:
      # 配置文件
      - ./config.conf:/app/config.conf:ro
      
      # 日志目录
      - ./logs:/app/logs
      
      # 备份目标目录
      - /path/to/backups:/backups
      
      # 源数据目录 (只读)
      - /path/to/source:/data:ro
    
    restart: unless-stopped
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
